version: '3.8'

services:
  # Payment API Service
  payment-api:
    build:
      context: ../src/PaymentSystem.PaymentApi
      dockerfile: Dockerfile
    image: payment-system/payment-api:latest
    container_name: payment-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - JsonKeyStore__KeyStoreFilePath=/app/keys/payment-keys.json
    ports:
      - "7000:443"
      - "5000:80"
    volumes:
      - ../src/PaymentSystem.PaymentApi/keys:/app/keys:ro
      - payment-logs:/app/logs
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/api/payment/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - key-generator

  # Client API Service
  client-api:
    build:
      context: ../src/PaymentSystem.ClientApi
      dockerfile: Dockerfile
    image: payment-system/client-api:latest
    container_name: client-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PaymentApi__BaseUrl=https://payment-api:443
    ports:
      - "7001:443"
      - "5001:80"
    volumes:
      - client-logs:/app/logs
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/api/customer/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      payment-api:
        condition: service_healthy

  # Key Generator Service (runs once)
  key-generator:
    build:
      context: ../tools/PaymentSystem.KeyManager
      dockerfile: Dockerfile
    image: payment-system/key-manager:latest
    container_name: key-generator
    environment:
      - OUTPUT_PATH=/keys/payment-keys.json
      - ENVIRONMENTS=development,staging,production
      - KEY_SIZE=2048
    volumes:
      - ../src/PaymentSystem.PaymentApi/keys:/keys
    command: >
      dotnet PaymentSystem.KeyManager.dll generate
      --output /keys/payment-keys.json
      --environments development staging production
      --key-size 2048
    networks:
      - payment-network
    restart: "no"

volumes:
  payment-logs:
    driver: local
  client-logs:
    driver: local

networks:
  payment-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16